# This is a basic workflow

name: CI

on: push

jobs:
  code_quality:
    runs-on: ubuntu-latest
    name: Checks with black, isort and possibly run tests
    container: python:3.12

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run script
        run: |
          pip install black isort pytest
          pip install -r requirements.txt
          ls -la
          isort --profile=black --check .
          py.test tests